### ISSUE TITLE
NameError: name 'GF' is not defined

### ISSUE THREAD

**Issue by SaSam5666** [kate-jet007/Pythagorean-formula-#1]
I received this below error
"
C:\Pythagorean-formula--main\Pythagorean-formula--main>python formula.py
Traceback (most recent call last):
  File "formula.py", line 8, in <module>
    K = GF(p)
NameError: name 'GF' is not defined
"

**Comment by jjeett0007** [comment]
it is just a formula stored in python file you can only use that in sage work sheet
    On Wednesday, August 25, 2021, 06:15:30 PM GMT+1, SaSam5666 ***@***.***> wrote:  
 
 


I received this below error
"
C:\Pythagorean-formula--main\Pythagorean-formula--main>python formula.py
Traceback (most recent call last):
File "formula.py", line 8, in 
K = GF(p)
NameError: name 'GF' is not defined
"

**Comment by pathianil143** [comment]
ans

**Comment by jjeett0007** [comment]
use this formula in sageMath colcal calculator

**Comment by jjeett0007** [comment]
s
